### ISSUE TITLE
enhancement: installation progress bar

### ISSUE THREAD

**Issue by yonicd** [metrumresearchgroup/pkgr#129]
While the installation is happening a progress bar for 

`n_pkgs_installed/N_TOTAL_PKGS`

would be nice to give the user a reference of what is left in the install task given that in most cases a lot of packages are imported along with the original list in the yml

**Comment by dpastoor** [comment]
so I gave a crack at this. The problem is that progress bars inherently must control the entire console. They are constantly flushing the buffer/screen and redrawing to present the progress bar itself. This causes some very problematic behavior with the stream of log file results coming across, which the progress bar keeps on wiping out. 

As such to implement a _true_ progress bar, would be a significant re-architecture, however the request to at least have a sense of where the installation is is quite reasonable and could be at least logged more effectively.

Priority wise, we are working hard on getting 0.5 out, so this is in the roadmap to re-consider as a future enhancement.

**Comment by dpastoor** [comment]
@yonicd in 0.5.1 we have implemented at least a `remaining` token:

![image](https://user-images.githubusercontent.com/3196313/69978608-c3f1ba80-14fa-11ea-8098-a3f6b6c9b6fb.png)

In combination with the plan, which will specify the initial number to install, this should give a sense of the countdown
