### ISSUE TITLE
preinstalling dependent system library prior to installing an R package

### ISSUE THREAD

**Issue by yonicd** [metrumresearchgroup/pkgr#130]
I am trying to install the [units](https://github.com/r-quantities/units) package and am getting the error

<details><summary>error message</summary>

```
ERRO[0003] cmd output                                    exitCode=1 package=units stderr="* installing *source* package 'units' ...\n** package 'units' successfully unpacked and MD5 sums checked\nconfigure: error: in `/tmp/RtmpVsg0mQ/R.INSTALL18b5706847ff/units':\nconfigure: error: \n--------------------------------------------------------------------------------\n  Configuration failed because libudunits2.so was not found. Try installing:\n    * deb: libudunits2-dev (Debian, Ubuntu, ...)\n    * rpm: udunits2-devel (Fedora, EPEL, ...)\n    * brew: udunits (OSX)\n  If udunits2 is already installed in a non-standard location, use:\n    --configure-args='--with-udunits2-lib=/usr/local/lib'\n  if the library was not found, and/or:\n    --configure-args='--with-udunits2-include=/usr/include/udunits2'\n  if the header was not found, replacing paths with appropriate values.\n  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.\n--------------------------------------------------------------------------------\n\nSee `config.log' for more details\nERROR: configuration failed for package 'units'\n* removing '/tmp/WJGSAPGATLMO/units'\n" stdout="configure: units: 0.6-3\nchecking whether the C++ compiler works... yes\nchecking for C++ compiler default output file name... a.out\nchecking for suffix of executables... \nchecking whether we are cross compiling... no\nchecking for suffix of object files... o\nchecking whether we are using the GNU C++ compiler... yes\nchecking whether g++ accepts -g... yes\nchecking how to run the C++ preprocessor... g++ -E\nchecking for grep that handles long lines and -e... /bin/grep\nchecking for egrep... /bin/grep -E\nchecking for ANSI C header files... yes\nchecking for sys/types.h... yes\nchecking forsys/stat.h... yes\nchecking for stdlib.h... yes\nchecking for string.h... yes\nchecking for memory.h... yes\nchecking for strings.h... yes\nchecking for inttypes.h... yes\nchecking for stdint.h... yes\nchecking for unistd.h... yes\nchecking for stdbool.h that conforms to C99... no\nchecking for _Bool... no\nchecking forerror_at_line... yes\nchecking for gcc... gcc -std=gnu99\nchecking whether we are using the GNU C compiler... yes\nchecking whether gcc -std=gnu99 accepts -g...yes\nchecking for gcc -std=gnu99 option to accept ISO C89... none needed\nchecking for XML_ParserCreate in -lexpat... yes\nchecking udunits2.h usability... no\nchecking udunits2.h presence... no\nchecking for udunits2.h... no\nchecking udunits2/udunits2.h usability... no\nchecking udunits2/udunits2.h presence... no\nchecking for udunits2/udunits2.h... no\nchecking for ut_read_xml in -ludunits2... no\n"
WARN[0003] error installing                              err="exit status 1"
```

</details>

is there a way to add onto the pkgr.yml definitions to preinstall a system library that will be needed for the packages listed for installation? or is this a step the user needs to do independent of pkgr?

in this case it would be 

```
sudo apt-get install libudunits2-dev
```

the travis equivalent would be using [addons](https://docs.travis-ci.com/user/installing-dependencies#installing-packages-with-the-apt-addon)

```yml
addons:
  apt:
    update:
    - true
    packages:
    - libudunits2-dev
```

**Comment by dpastoor** [comment]
this is unlikely to be in scope for pkgr in the (nearish) term, which focuses, for now, on the packages themselves and leaves the system deps up to the user. 

In particular, how do you detect and declare this for multiple platforms and OS flavors. Your syntax is travis-esque, which works, if you "only" care about ubuntu/debian flavors of linux. But this should be reasonably portable and what happens if someone wants redhat (yum), osx (homebrew), etc. 

There are some initiatives to try to track this down, such as: `https://github.com/r-hub/sysreqsdb` but it is a hard problem in-itself. 

Furthermore, many of these would require privileged use to install correctly, and could be open to a huge amount of nuance between how organizations manage such applications. As it exists, pkgr does not require admin privs and can be dumped onto just about any system, even without install rights (since don't really need to 'install' anything, just invoke the binary). 

That said, an upstream, composeable package, that can support such activities is probably in the cards.

A shorter term objective could be to parse failures and more clearly articulate/guess what is needed for a user to install. especially for particular dependency patterns.

**Comment by dpastoor** [comment]
closed but tracked in icebox of roadmap as a known request for future consideration as a potential expanded scope
