### ISSUE TITLE
what to check in to the repo

### ISSUE THREAD

**Issue by janelleh** [metrumresearchgroup/pkgr#214]
With the new setup, it isn't so intuitive as to what we should be checking in to the repo. For the most part, I think most people are accustomed to checking in everything except for the lib directory. I see that the libraries are now in the renv folder. It might be useful to clarify what to check in, for example not the renv folder? What is the .Rhistory file, .gitignore, etc.? Should they be checked in? Again, just coming from the way we are accustomed to doing things, it will save headache in trying to figure out where the libraries live and what we should/shouldn't check in. Will running the .ignore_libs() function work in the same way it used to, preventing the /lib directory (which is now renv?) from being added/checked in? 
Thanks.

**Comment by dpastoor** [comment]
renv automatically drops the relevant _git_ ignore files to ignore all libraries. Since you should only be using MPN snapshots, there is no need to check in any source tarballs since you can reproduce your results from said snapshots as they are immutable.

What I am _not_ sure of is whether it drops the proper svn ignore? equivalents. I know there is such a think but am not too familiar with it.

Lets move this convo to the project template repo as this isn't really a pkgr question, rather than the msproject template question. These are very salient questions that we need to address via SVN as well for people that aren't yet able to migrate to ghe for project work internally
