### ISSUE TITLE
Rpath environment variable not propagating from pkgr yaml

### ISSUE THREAD

**Issue by andersone1** [metrumresearchgroup/pkgr#383]
@dpastoor 
@Dreznel 

# Description:
Checked that `${R_EXE_3_6}` returns correct path, but `pkgr install` did not pick this up.

# Screen shot:
![image](https://user-images.githubusercontent.com/28537780/132378578-5e0e6610-5b7c-452f-9155-5a456da2905b.png)

# Pkgr version:
pkgr `v3.0.0-rc1` 

# Metworx version:
![image](https://user-images.githubusercontent.com/28537780/132378758-4f6f3a4f-6f5a-47ae-b502-8859fea9f8f1.png)

# Current workaround, hardcode path:

![image](https://user-images.githubusercontent.com/28537780/132379025-d31e35c9-d213-4301-80ca-7ba424e7d103.png)

**Comment by dpastoor** [comment]
I can confirm/reproduce this behavior... but I'm somewhat perplexed. This is an untouched area of code, i've added some verbose logging and it seems the environment variables set are no longer being propogated. I'm not sure if this was due to an upgrade in the go version or what. Under investigation...

**Comment by dpastoor** [comment]
false alarm - I've determined this is because if an environment variable is just sourced but not _exported_ in the shell session it will not propagate to the pkgr subprocess. We need to update the metworx configuration to properly re-export
