### ISSUE TITLE
Documentation Request: User-focused Changelog

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/pkgr#397]
I see that pkgr 3.0 is out.  Congratulations!

It is a bit hard to decipher what is different from 2.0.  Is there a user-focused changelog or news file available?

**Comment by seth127** [comment]
Hello Bill. Thanks for checking in and sorry for the delay. We have added some notes to the [release page](https://github.com/metrumresearchgroup/pkgr/releases/tag/v3.0.0). They are fairly light, largely because the main effort in this release was towards improving our test suite and wiring it into CI. 

Please reach out if you have other more specific questions. We are currently working on revamping the documentation as a whole (similar to the previously mentioned effort on the test suite) so hopefully that will help as well.

Best, Seth

**Comment by billdenney** [comment]
Thanks, the added release notes help me understand.
