### ISSUE TITLE
clean/invalidate caches

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#40]
should clean at least:

- [x] package cache
  - [x] binary
  - [x] src

package cache located at `Cache`

## scoping expectations:

* Need an api proposal (eg how would users do this) 
* potential code areas of note
* estimated time
* risk assessment

**Comment by Dreznel** [comment]
## General thoughts and relevant code sections

After a pass through some parts of the code, I this seems to just require clearing a directory/items from a directory that is set by this function call: https://github.com/metrumresearchgroup/pkgr/blob/aca7e894242db6b2f18c3886152f857f0d565b7c/cmd/install.go#L57.

That call includes a call to the userCache function from utils.go in the same package.

## API Proposal
The easiest way to let users do this would probably be to just add a "pkgr clean" subcommand that both clears the cache and the pkgdb. If we don't want this "clear all" by default, we could add sub-subcommands (sort of like git does) such as "pkgr clean cache", "pkgr clean database <database, "" = -A for all>", and "pkgr clean -A" for all.

I'm proposing a general solution here because I like the idea of a "pkgr clean -A" or "pkgr reset --hard" command to fully reset the state of your pkgr setup, but in reality I think that #49 should probably have a more nuanced solution that checks for updates.

## Estimated Time
To just add the "clear the cache folder" subcommand would probably take me between four and twelve hours to implement, and between four and eight hours to write tests for (I'll have to learn how to use afero, which I'm unfamiliar with). These are rough estimates, obviously, but that's what it feels like assuming my assessments are correct.

**Comment by Dreznel** [comment]
We could also pass in the "clear cache" option as a flag on the `pkgr install` command, but I think that this would result in a more complicated change.

**Comment by dpastoor** [comment]
Great proposal, lets do the following:

* all

```
pkgr clean --all
```

* crandbs

```
pkgr clean --pkgdb    // all
pkgr clean --pkgdb="CRAN"    // specific db
pkgr clean --pkgdb="CRAN,r_validated" // comma separated slice
pkgr clean --pkgdb="CRAN, r_validated" // whitespace should be ok?
```

* package cache
   * binary
    * src

```
pkgr clean --cache
pkgr clean --cache // CRAN/binary or CRAN/src, etc ...? 
pkgr clean --cache --src= --binary= ?
```
