### ISSUE TITLE
cannot install pkgr via homebrew

### ISSUE THREAD

**Issue by pharmdwoman** [metrumresearchgroup/pkgr#400]
Got error message from homebrew below. Is there a workaround to install pkgr on macbook Air? 
Thanks,
Thuy 

![Screen Shot 2022-03-04 at 11 07 49 AM](https://user-images.githubusercontent.com/29149465/156798255-e5bc81b3-d85c-4ed2-8ac5-f39acf017ab8.png)

**Comment by kyleam** [comment]
Thanks for reporting.

Without looking into this more closely or asking around, my guess is that the problem is that, even though pkgr's formula does _not_  use the now-invalid `:unneeded` because its formula was generated with a goreleaser that does not use `:unneded` (goreleaser issue 2591), the tap itself is failing due to the other formula that were generated with an older goreleaser (and thus use `:unneeded`).  IIRC this used to be a warning, but must have been promoted to an error by the latest homebrew.

Until this is resolved one workaround is to download the binary and put it somewhere that's on your `$PATH`:

```console
$ curl -fSsL \
 'https://github.com/metrumresearchgroup/pkgr/releases/download/v3.0.0/pkgr_3.0.0_darwin_amd64.tar.gz' |
  tar -z --extract --to-stdout >pkgr
$ sha1sum pkgr
9a1ba1e1f9d42d4bf362b9c8366eb74052688cd5  pkgr
$ chmod +x pkgr
$ ./pkgr --version
v3.0.0
```

**Comment by pharmdwoman** [comment]
I was not able to download and install per your instructions above. My mac doesn't recognize the commands(?). I downloaded the package via github but still could not install the package through the terminal or directly in RStudio. Any other ways?

**Comment by kyleam** [comment]
Hmm, my guess is that that `tar` invocation is GNU-specific and incompatible with the `tar` that ships with macOS.

Here's a recipe to do it from within R:

```R
> download.file("https://github.com/metrumresearchgroup/pkgr/releases/download/v3.0.0/pkgr_3.0.0_darwin_amd64.tar.gz", "pkgr.tar.gz")
> untar("pkgr.tar.gz")
```

It looks like the file already has its executable bit, so you don't need to worry about the `chmod` call.

```
> file.info("pkgr")$mode
[1] "755"
```

Then just move `pkgr` to somewhere on your `$PATH` (or always call it with a leading path).

**Comment by pharmdwoman** [comment]
That worked! Thank you so much for your help.
-Thuy

**Comment by kyleam** [comment]
Just a note: the `brew tap metrumresearchgroup/tap` errors should be fixed once https://github.com/metrumresearchgroup/homebrew-tap/pull/1 is merged.

**Comment by kyleam** [comment]
`brew tap metrumresearchgroup/tap` should work now.
