### ISSUE TITLE
Cannot install cmdstanr

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/pkgr#403]
When trying to update everything on my system, I got the following error from trying to install `cmdstanr`.  My pkgr.yml (renamed to .txt) file is here: [pkgr.txt](https://github.com/metrumresearchgroup/pkgr/files/8693617/pkgr.txt)

I'm running Windows 10 with R 4.1.2.

```
time="2022-05-14T13:26:54-04:00" level=error msg="cmd output" exit_code=1 output="* installing *binary* package 'cmdstanr' ...\r\ncp: unknown option -- )\nTry '/usr/bin/cp --help' for more information.\nERROR: installing binary package failed\r\n* removing 'C:/Users/BILLDE~1/AppData/Local/Temp/BTAOAWYLGXTJ/cmdstanr'\r\n" package=cmdstanr stderr="* installing *binary* package 'cmdstanr' ...\r\ncp: unknown option -- )\nTry '/usr/bin/cp --help' for more information.\nERROR: installing binary package failed\r\n* removing 'C:/Users/BILLDE~1/AppData/Local/Temp/BTAOAWYLGXTJ/cmdstanr'\r\n" stdout=
time="2022-05-14T13:26:54-04:00" level=warning msg="error installing" err="exit status 1"
```

**Comment by kyleam** [comment]
Have you checked whether this is a general issue that's not specific to pkgr?  That pkgr configuration has

```
Repos:
- CRAN: "https://cran.microsoft.com/snapshot/2022-05-14"
- cmdstanrrepo: "https://mc-stan.org/r-packages/"
```

Do you see the same failure if you try to install cmdstanr from the same repos in another way?  For example:

```
# in some scratch directory
$ Rscript -e 'renv::init()'
$ Rscript -e 'renv::install("cmdstanr", repos = c("https://cran.microsoft.com/snapshot/2022-05-14", "https://mc-stan.org/r-packages/"))'
```

**Comment by billdenney** [comment]
I just checked, and this works:

`install.packages("cmdstanr", repos = c("https://cran.microsoft.com/snapshot/2022-05-14", "https://mc-stan.org/r-packages/"))`

**Comment by seth127** [comment]
I agree with @kyleam here. I like your thinking @billdenney but I think we should be careful about trying to diagnose these kind of failures and automatically giving advice on how to fix them. Feels like it might cause more problems than it would fix...

It seems like the problem here is on the `cmdstanr` side, and @kyleam has filed an issue with them already ([here](https://github.com/stan-dev/r-packages/issues/7) if you missed it, thanks Kyle!)

As for fixing your specific problem @billdenney , I assume this works because it's installing from the binary, right?

```r
install.packages("cmdstanr", repos = c("https://cran.microsoft.com/snapshot/2022-05-14", "https://mc-stan.org/r-packages/"))
```

Have you tried getting rid of the source Customization in your `pkgr.yml` and installing from that? I'm not aware of the previous issue with `cmdstanr` and binary, but I know the package is fairly young, so maybe it's a thing of the past by now?

**Comment by billdenney** [comment]
Thanks for the research into the issue.  It makes sense not to go too far in diagnosing the issue unless you have full control over it.  So, all of your thoughts make sense.

I believe that cmdstanr only intended to ship source packages.  So, I think that the issue @kyleam raised over there is real.  Regardless, I will close this as it seems to be a very rational "wontfix" issue.
